### ISSUE TITLE
ERROR: Service 'php' failed to build

### ISSUE THREAD

**Issue by cdaecke** [danielnv18/php-sqlsrv-example#1]
While searching the net for a Docker setup wich supports PHP and MSSQL, I came accros your posting [here](https://daniel.noyola.dev/sqlsrv-php/). Thanks a lot for sharing your knowledge!

Now, when I try to run your configuration, it fails with the following error:

> Package libbz2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  bzip2

> E: Package 'libbz2' has no installation candidate
ERROR: Service 'app' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y locales unixodbc libgss3 odbcinst     devscripts debhelper dh-exec dh-autoreconf libreadline-dev libltdl-dev     tdsodbc unixodbc-dev wget unzip libbz2 apt-transport-https     libfreetype6-dev libmcrypt-dev libjpeg-dev libpng-dev     && rm -rf /var/lib/apt/lists/*     && docker-php-ext-install pdo     && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen' returned a non-zero code: 100

After removing `libbz2` from the Dockerfile, I get the following error:

> ERROR: Service 'php' failed to build: The command '/bin/sh -c pecl install WINCACHE-1.3.7.12 pdo_sqlsrv-5.6.1 sqlsrv-5.6.1     && docker-php-ext-enable pdo_sqlsrv sqlsrv     && docker-php-ext-install -j$(nproc) gd     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/' returned a non-zero code: 1

Do you have any hint, how to possibly fix this error and get it up an running?

I am running Docker Dektop community (Version 2.2.0.0) on a Mac.

**Comment by danielnv18** [comment]
Hi it looks like there are some problems with php 7.4 and the latest driver of sql server. Try to set an specific version of php like `php:7.3-fpm`. If that doesn't work I updated the `Dockerfile`. Let me know if that worked!

**Comment by cdaecke** [comment]
Thanks for your quick feedback!

You are right, with `php:7.3-fpm` it runs through, but I still had to remove `libbz2`. Nevertheless I don't get any response, when calling http://localhost:9000. How do I call the `index.php` in the browser?

**Comment by cdaecke** [comment]
Got it to work, thanks a lot!
